create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  name text not null unique,
  email text unique,
  password_hash text,
  prediction_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.results (
  id smallint primary key check (id = 1),
  results_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value text not null
);

insert into public.results (id, results_json)
values (1, '{}'::jsonb)
on conflict (id) do nothing;

insert into public.settings (key, value)
values ('registrations_open', 'true')
on conflict (key) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists participants_set_updated_at on public.participants;
create trigger participants_set_updated_at
before update on public.participants
for each row execute function public.set_updated_at();

drop trigger if exists results_set_updated_at on public.results;
create trigger results_set_updated_at
before update on public.results
for each row execute function public.set_updated_at();
